# Main Menu Starts Here...

  [[main]]
    name = "Home"
    url = "/"
    weight = "1"

  [[main]]
    name = "Learning Guides"
    url = "/knowledge-base/"
    weight = "2"

  [[main]]
    name = "Buying Guides"
    url = "/buying-guides/"
    weight = "3"
	
  [[main]]
    name = "Motherboards"
    url = "/motherboards/"
    weight = "4"
    
  [[main]]
    name = "Monitors"
    url = "/monitors/"
    weight = "5"

# Footer Menu Starts Here...

  [[footer]]
    name = "Terms and Conditions"
    url = "/terms-of-service/"
    weight = "1"

  [[footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = "2"

  [[footer]]
    name = "Affiliate Disclosure"
    url = "/affiliate-disclosure/"
    weight = "3"

  [[footer]]
    name = "About US"
    url = "/about-us/"
    weight = "4"

  [[footer]]
    name = "Contact US"
    url = "/contact-us/"
    weight = "5"
    
  [[footer]]
    name = "Sitemap"
    url = "/sitemap.xml/"
    weight = "5"
